image: "python:3.8"

variables:
  PIPENV_VENV_IN_PROJECT: 1
  PIPENV_IGNORE_VIRTUALENVS: 1

before_script:
  - python --version
  - pip install pipenv
  - pipenv sync -d

stages:
  - test
  - deploy

lint:
  stage: test
  script:
    - pipenv run flake8 .
